import ProbNetKAT.DCPO
import ProbNetKAT.MeasureExtension
import ProbNetKAT.Scott
import ProbNetKAT.Cantor

/-!

# ProbNetKAT

Formalization of ProbNetKAT.

- [Cantor](ProbNetKAT/Cantor.html)
- [Scott](ProbNetKAT/Scott.html)
- [Measure extension](ProbNetKAT/MeasureExtension.html)

## Main theorems and definitions

- `ProbNetKAT.cantor_borel_eq_scott_borel`: Connecting the Borel sets generated by the two
  topologies.

-/
