import MDP.MarkovChain
import MDP.Paths.Prob

namespace MDP

variable {State Act : Type*}

@[grind =, simp]
theorem MScheduler.P'_isSome {M : MDP State Act} (ℒ : 𝔏[M]) : (M.P s (ℒ {s})).isSome = true := by
  simp [M.P_isSome_iff]
  have := (ℒ.toScheduler.property {s})
  simpa [act, M.P_isSome_iff]

@[grind =, simp]
theorem Scheduler.P'_isSome {M : MDP State Act} (𝒮 : 𝔖[M]) (π : M.Path) :
    (M.P π.last (𝒮 π)).isSome = true := by
  have := (𝒮.property π)
  simpa [act, M.P_isSome_iff]

def inducedMC₀ (M : MDP State Act) (ℒ : 𝔏[M]) (ι : State) : MarkovChain State where
  P s := (M.P s (ℒ {s})).get (by simp)
  ι := ι

variable {M : MDP State Act} {ℒ : 𝔏[M]} {ι : State}

@[grind =, simp]
theorem inducedMC₀_P : (M.inducedMC₀ ℒ ι).P s s' = M.P s (ℒ {s}) s' := by
  simp [inducedMC₀]

def Path.toMC₀ (π : M.Path) (h : π.Prob ℒ ≠ 0) (h' : π[0] = ι := by rfl) :
    (M.inducedMC₀ ℒ ι).Path where
  states := π.states
  initial := by grind [inducedMC₀]
  property := by
    simp
    simp [Prob, Finset.prod_eq_zero_iff] at h
    intro i hi
    specialize h ⟨i, by grind⟩
    grind

/-- The probability of a path `π` with memoryless scheduler `ℒ` is the measure of the cylinder set
  generated by `π` on the induced Markov chain using `ℒ`. -/
theorem inducedMC₀_cyl (π : M.Path) (h' : π.Prob ℒ ≠ 0) :
    (M.inducedMC₀ ℒ π[0]).Pr (π.toMC₀ h').Cyl = π.Prob ℒ := by
  simp [MarkovChain.Pr_cyl, Path.toMC₀, Path.Prob]
  rfl

/-- info: 'MDP.inducedMC₀_cyl' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms inducedMC₀_cyl

noncomputable def Path.pmf (π : M.Path) (𝒮 : 𝔖[M]) : PMF M.Path :=
  ((M.P π.last (𝒮 π)).get (by simp)).bindOnSupport
    (fun s hs ↦ PMF.pure (π.extend ⟨s, by simp_all [MDP.succs_univ, MDP.succs]; grind⟩))

noncomputable def inducedMC (M : MDP State Act) (𝒮 : 𝔖[M]) (ι : State) :
    MarkovChain M.Path where
  P π := π.pmf 𝒮
  ι := {ι}

variable {𝒮 : 𝔖[M]}

@[grind =, simp]
theorem inducedMC_P : (M.inducedMC 𝒮 ι).P s s' = s.pmf 𝒮 s' := by
  simp [inducedMC]

def Path.toMC (π : M.Path) (h : π.Prob 𝒮 ≠ 0) (h' : π[0] = ι := by rfl) :
    (M.inducedMC 𝒮 ι).Path where
  states := List.ofFn (n:=‖π‖) (π.take ·.val)
  initial := by grind [inducedMC]
  property := by
    simp
    simp [Prob, Finset.prod_eq_zero_iff] at h
    intro i hi
    specialize h ⟨i, by grind⟩
    simp [pmf]
    use π[i + 1]
    use by grind
    ext
    · simp; grind
    · simp [take, extend]
      grind

set_option maxHeartbeats 500000 in
/-- The probability of a path `π` with scheduler `𝒮` is the measure of the cylinder set generated
  by `π` on the induced Markov chain using `𝒮`. -/
theorem inducedMC_cyl (π : M.Path) (h' : π.Prob 𝒮 ≠ 0) :
    (M.inducedMC 𝒮 π[0]).Pr (π.toMC h').Cyl = π.Prob 𝒮 := by
  simp [MarkovChain.Pr_cyl, Path.toMC, Path.Prob]
  simp [Path.pmf]
  apply Finset.prod_bij_ne_one fun ⟨x, _⟩ _ _ ↦ ⟨x, by grind⟩
  · grind
  · grind
  · simp_all only [ne_eq, Finset.mem_univ, exists_true_left, forall_const]
    intro ⟨i, hi⟩ h
    use ⟨i, by grind⟩
    simp
    rw [tsum_eq_single π[i + 1]]
    · split_ifs
      · simp_all
      · grind
      · simp_all
    · simp_all only [ne_eq, dite_eq_left_iff, ite_eq_right_iff, imp_false]
      simp_all [Path.take, Path.extend]
      intro s' hs' h''
      contrapose! hs'
      have :
            ((List.take (i + 1 + 1) π.states)[i + 1]'(by grind))
          = ((List.take (i + 1) π.states ++ [s'])[i + 1]'(by grind)) := by grind
      grind
  · simp_all only [ne_eq, Finset.mem_univ, forall_true_left]
    intro ⟨i, hi⟩ h
    rw [tsum_eq_single (π[i + 1]'(by grind))]
    · simp_all only
      split_ifs with h h'
      · grind
      · grind
      · contrapose! h'
        ext
        · simp; grind
        · simp [Path.take, Path.extend]; grind
    · simp_all only [ne_eq, dite_eq_left_iff, ite_eq_right_iff, imp_false]
      intro s' hs' h
      contrapose! hs'
      simp [Path.take, Path.extend] at hs'
      have :
            ((List.take (i + 1 + 1) π.states)[i + 1]'(by grind))
          = ((List.take (i + 1) π.states ++ [s'])[i + 1]'(by grind)) := by grind
      grind

/-- info: 'MDP.inducedMC_cyl' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms inducedMC_cyl

end MDP
